/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import java.util.Scanner;

public class App {


    // public String getGreeting() {
    //     return "Hello World!";
    // }

    public static void main(String[] args) {

      
        Scanner sc = new Scanner(System.in);

        boolean continuar = true;
        do{

        System.out.println("Selecione uma opção:");
        System.out.println("[1] - Celsius para Fahrenheit");
        System.out.println("[2] - Fahrenheit para Celsius");
        int opcao = sc.nextInt();

        if (opcao == 1) {
            System.out.println("Digite a temperatura em Celsius:");
            double celsius = sc.nextDouble();
            double fahrenheit = ConvertTo.celsiusToFahrenheit(celsius);
            System.out.printf("Temperatura em Fahrenheit: %.2f%n", fahrenheit);
        } else if (opcao == 2) {
            System.out.println("Digite a temperatura em Fahrenheit:");
            double fahrenheit = sc.nextDouble();
            double celsius = ConvertTo.fahrenheitToCelsius(fahrenheit);
            System.out.printf("Temperatura em Celsius: %.2f%n", celsius);
        } else {
            System.out.println("Opção inválida.");
        }

        System.out.println("Deseja continuar? (s/n)");
        char resposta = sc.next().charAt(0);
        if (resposta == 'n' || resposta == 'N') {
            System.out.println("Resposta inválida. Encerrando o programa.");
            continuar = false;
        } else if (resposta != 's' && resposta != 'S') {
            continuar = true;
        }
        }while (continuar == true);

            sc.close();

    }
}
 