/*
 * This source file was generated by the Gradle 'init' task
 */
package org.example;

import org.junit.jupiter.api.Test;
import static org.junit.jupiter.api.Assertions.*;

class AppTest {
    @Test void appHasAGreeting() {
        assertNotNull(ConvertTo.celsiusToFahrenheit(25.1), "app should have a greeting");
    }
    @Test void isEqualToFahrenheight() {
        assertEquals(ConvertTo.celsiusToFahrenheit(25.0), 77.00);
    }
}
