name: Build
on:
  push:
    branches:
      - main
jobs:
  DigaOla:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Diga Ola
        uses: ./.github/actions/DigaOla-Action

  SetupGradle:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v2
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Setup Gradle
        uses: gradle/actions/setup-gradle@v4
  PermicaoGradlew:
    runs-on: ubunto-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Set Gradle Permission
        uses: ./.github/actions/PermicaoGradlew
  BuildGradle:
    runs-on: ubunto-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build Gradlew
        uses: ./.github/actions/Build